### ISSUE TITLE
Cannot stream multiple accounts

### ISSUE THREAD

**Issue by olganovosad** [LaboratoryGA/cla-cmp-fb-tweet#1]
Hello,

I've tried to stream multiple FB pages.

I've created new App id and app secret, and these as per instructions:

$cfg_social_streams = [
    [
        'provider'          => 'facebook',
        'appID'             => '372549199603943',
        'appSecret'         => 'cf158a5de96d69de81452c80cf761e7d',
        'resource'          => 'iriepixel'

```
    'provider'          => 'facebook',
    'appID'             => '821107907985386',
    'appSecret'         => '91980fc51aec5b98e1acb3bd0b9c8116',
    'resource'          => 'AlinaCraft.handmade'
],

[
    'provider'          => 'twitter',
    'consumerKey'       => 'fII0BHDMcyKDuNXQzZjPYNyr3',
    'consumerSecret'    => 'ydREhBecPy7dVy9PQejr8jlD96F4cgdkgzj3MyzKrjVIKPxPCB',
    'screenName'        => 'olia_cla'
],
```

];

I'm using the following component code:

component class="SocialComponent" social_filter="fb, twitter" (I have removed <> so the code doesn't disappear from the ticket)

It doesn't display posts from both FB pages, it breaks my testing system.

Please let me know if I'm missing something.

Thanks

**Comment by LaboratoryGA** [comment]
You've unfortunately lumped 2 providers into a single array. The correct way to do this would be as follows:

``` php
$cfg_social_streams = [
    [
        'provider' => 'facebook',
        'appID' => '372549199603943',
        'appSecret' => 'cf158a5de96d69de81452c80cf761e7d',
        'resource' => 'iriepixel'
    ],
    [
        'provider' => 'facebook',
        'appID' => '821107907985386',
        'appSecret' => '91980fc51aec5b98e1acb3bd0b9c8116',
        'resource' => 'AlinaCraft.handmade'
    ],
    [
        'provider'          => 'twitter',
        'consumerKey'       => 'fII0BHDMcyKDuNXQzZjPYNyr3',
        'consumerSecret'    => 'ydREhBecPy7dVy9PQejr8jlD96F4cgdkgzj3MyzKrjVIKPxPCB',
        'screenName'        => 'olia_cla'
    ],
];
```

**Comment by LaboratoryGA** [comment]
Sorry, I also forgot - in order to use multiple instances of a single provider type, you **must** specify the "name" parameter thus:

``` php
    [
        'provider' => 'facebook',
        'name' => 'irie',
        'appID' => '372549199603943',
        'appSecret' => 'cf158a5de96d69de81452c80cf761e7d',
        'resource' => 'iriepixel'
    ]
```

Each name must be unique, or they will simply be overridden.
