### ISSUE TITLE
IE9, 10, 11 - some of the emoji are not displayed

### ISSUE THREAD

**Issue by olganovosad** [LaboratoryGA/cla-cmp-fb-tweet#10]
Hello,

If you check emoji in IE9, 10, 11  - some of them are displayed as expected.

Please see screenshot:

![emoji](https://cloud.githubusercontent.com/assets/8656805/7562830/88eb13d4-f7cf-11e4-8a4d-f422e92dc3f3.png)

**Comment by LaboratoryGA** [comment]
Then I will need help locating a different Emoji library, because this is handled by a 3rd party module.

**Comment by LaboratoryGA** [comment]
I am open to suggestions on how to deal with this. I can only find a single PHP Emoji library, which is already being used: http://code.iamcal.com/php/emoji/

**Comment by LaboratoryGA** [comment]
Won't fix
