### ISSUE TITLE
Filtering by instance - all posts are still visible

### ISSUE THREAD

**Issue by olganovosad** [LaboratoryGA/cla-cmp-fb-tweet#11]
Hello,

Please let me know if I'm missing something here.

I tried to filter by instance, however, I can still see posts from both pages and, also, twitter.

I tried adding both name and resource, but neither is working on my side.

The code I have used:

component class="SocialComponent" social_filter="facebook::irie"

component class="SocialComponent" social_filter="facebook::iriepixel"

Thank you.

**Comment by LaboratoryGA** [comment]
Apologies, the documentation is wrong - you should be using `source_filter`, not `social_filter` I will update the README to reflect this correctly.

**Comment by LaboratoryGA** [comment]
I've updated the documentation.

**Comment by olganovosad** [comment]
thank you.

It now says: No posts yet

Tried for both pages I'm using.

**Comment by LaboratoryGA** [comment]
Please send me the code snippet. I'm using the exact configuration you uploaded on another ticket (the multiple facebook pages), and mine is working fine.

**Comment by olganovosad** [comment]
I've tried the following:

component class="SocialComponent" source_filter="facebook::irie"

component class="SocialComponent" source_filter="facebook::iriepixel"

OR

component class="SocialComponent" source_filter="facebook::AlinaCraft"

component class="SocialComponent" source_filter="facebook::AlinaCraft.handmade"

I have cleared cache and tried to logout and login back.

**Comment by LaboratoryGA** [comment]
Fixed - the correct format is the first (i.e. "facebook::irie")

**Comment by olganovosad** [comment]
Hello,

Let me know if I'm missing something.

This works as expected with irie page, but not with AlinaCraft. It still says "No posts yet" when I add "AlinaCraft": component class="SocialComponent" source_filter="facebook::AlinaCraft"

Thank you.

**Comment by LaboratoryGA** [comment]
Please send me your configuration file. You can wrap the source code by using three left single quote characters (these test areas appear to support Markdown).

**Comment by olganovosad** [comment]
```
$cfg_social_streams = [
    [
        'provider' => 'facebook',
        'name' => 'irie',
        'appID' => '372549199603943',
        'appSecret' => 'cf158a5de96d........c80cf761e7d',
        'resource' => 'iriepixel'
    ],
    [
        'provider' => 'facebook',
        'appID' => '821107907985386',
        'name' => 'AlinaCraft',
        'appSecret' => '91980fc51aec5b.........3bd0b9c8116',
        'resource' => 'AlinaCraft.handmade'
    ],
    [
        'provider'          => 'twitter',
        'consumerKey'       => 'fII0BHDMcyKDuNXQzZjPYNyr3',
        'consumerSecret'    => 'ydREhBecPy7dVy9PQe.......j3MyzKrjVIKPxPCB',
        'screenName'        => 'olia_cla'
    ],
];
```

**Comment by LaboratoryGA** [comment]
I've copied your configuration, and the filtering works perfectly. If I specify "facebook::AlinaCraft" in the source_filter, I only get those posts.

**Comment by olganovosad** [comment]
I have re-tested this and the issue doesn't exist anymore.

Thank you for looking into this.
