### ISSUE TITLE
Amend documentation for which stream to display

### ISSUE THREAD

**Issue by olganovosad** [LaboratoryGA/cla-cmp-fb-tweet#12]
Hello,

Could you, please, amend documentation for the following code:

component class="SocialComponent" source_filter="fb,twitter"

It should say facebook, not fb. When you limit which stream to display and leave fb it doesn't work. 

Let me know if I'm missing something.

Thank you.

**Comment by LaboratoryGA** [comment]
I may have to think how to word this better. The code `fb` is there for backward compatibility, but is only active _if an actual legacy configuration is found_. Not too sure how to convey all that. Leave this with me for a bit, and I'll come up with some way of documenting this better.

**Comment by LaboratoryGA** [comment]
Documentation updated - there actually already was a mention of "fb" support only being for legacy configurations, so simply updating the other references was sufficient.
