### ISSUE TITLE
Tags in shared content are not clickable in FB

### ISSUE THREAD

**Issue by olganovosad** [LaboratoryGA/cla-cmp-fb-tweet#13]
Hi,

I have a question. As you mentioned earlier the links are not clickable in FB. However, if I share a post and there were some users tagged or pages, should the tags be clickable in the shared content?

Currently, they are not. It is related to 11 issue in socialfeed project.

Thank you

**Comment by LaboratoryGA** [comment]
Not offered by API, as per original project scope.
