### ISSUE TITLE
The post limit is not applied for the shared content

### ISSUE THREAD

**Issue by olganovosad** [LaboratoryGA/cla-cmp-fb-tweet#3]
Hello,

If you apply a post limit, the shared content still showing up.

If you apply the limit if should hide the shared content as well and reveal this only when user clicks "..." to expand the post.

![sharedcontent](https://cloud.githubusercontent.com/assets/8656805/7429365/f5b08f9c-eff7-11e4-9d04-b63b4848b0cb.png)

**Comment by LaboratoryGA** [comment]
Apologies, I never even considered shared content would be so long.

**Comment by LaboratoryGA** [comment]
I'm going to have to look for another solution to this shortened content issue. I'm having a really hard time trying to make the title, content AND shared content all fall within a single length limit.

**Comment by LaboratoryGA** [comment]
Okay, I have switched to using a JavaScript library for doing this. The benefit is that it does collapsing again as another of your requests, but now the option `post_length` refers to pixels of height, not number of words.

**Comment by olganovosad** [comment]
Hello,

I don't think that the post length limit is working as expected. Currently, no matter how many characters I set in config, it fully hides the shared content and the original post text, when in this case the post should be followed by suspensions points and the arrow icon.

I have, also, set the length limit to 10 characters and the posts are displayed as cut off.

Please see screenshots:

![postlengthlimit](https://cloud.githubusercontent.com/assets/8656805/7562362/dbc9bf8c-f7cb-11e4-9c0e-c50727f7e9ce.png)
![postlength](https://cloud.githubusercontent.com/assets/8656805/7562363/dbce2f9a-f7cb-11e4-8330-85884065ee5e.png)

**Comment by LaboratoryGA** [comment]
Please pay attention to my last comment. **This no longer represents the number of words** but the number of pixel height of the post. The JavaScript library I am using uses pixels, not word count.

**Comment by olganovosad** [comment]
Hi Mike,

Could you please leave your feedback here if the solution is fine with you?

Thank you.

**Comment by michaelchristian** [comment]
I think pixels solution is ok, the trick is to make them so it won't cut  the letter, I know this is difficult due to letter sizing etc, perhaps put note / comments where designer can adjust this.

**Comment by LaboratoryGA** [comment]
Added to documentation
