### ISSUE TITLE
Expand/Collapse posts

### ISSUE THREAD

**Issue by olganovosad** [LaboratoryGA/cla-cmp-fb-tweet#4]
Hello,

Discussed this with Mike. Would be great to have "Show less" button or something similar to collapse the post.

I'm thinking to add triangle icons for "Show more" and "Show less".

So, if you have a long post still display the suspension points, but remove the hyperlink for these. Add a triangle icon, which points down after the suspension points,  to expand the post.

![example show more](https://cloud.githubusercontent.com/assets/8656805/7429464/8ccd9a7c-eff9-11e4-8c58-5fc133eff887.png)

And the triangle icon, which points up to collapse the post.

![show less](https://cloud.githubusercontent.com/assets/8656805/7429470/a7318e5a-eff9-11e4-9b14-6f21cf94f7b6.png)

Please let me know if this is possible.

Thank you.

**Comment by LaboratoryGA** [comment]
The task I was given specifically stated to make it behave like Facebook, which actually doesn't offer a "collapse" mechanism at all. Is this now a new requirement?

**Comment by olganovosad** [comment]
Mike,

Could you please leave a feedback here?

Thanks

**Comment by michaelchristian** [comment]
we can mark this as suggestion/enhancement request. nice to have to improve usability.

**Comment by LaboratoryGA** [comment]
This support is now in as a matter of moving to a JavaScript library, but I will look into making the arrows later.

**Comment by LaboratoryGA** [comment]
Actually, I just went ahead and implemented this
