### ISSUE TITLE
� symbol is displayed for some collapsed posts

### ISSUE THREAD

**Issue by olganovosad** [LaboratoryGA/cla-cmp-fb-tweet#5]
Hello,

There is collapsed post where � symbol is displayed. Is is due to unsupported character?

I have attached screenshot.

The language used in that post is Russian.

![unsupportedcharacter](https://cloud.githubusercontent.com/assets/8656805/7493394/60fb6124-f3f8-11e4-8a9f-ce58c7998555.png)

**Comment by LaboratoryGA** [comment]
This is odd, because the character displays fine once you expand the text.

**Comment by astax-t** [comment]
Hi Nathan,

Please use this function available in core to correctly truncate long strings:

```
/**
 * Limit length of string, add ... if string is cropped at the end
 *
 * @param string $str
 * @param int $max_length[optional] Default 40
 * @return string
 */
function trim_long_string($str, $max_length=40)
```

**Comment by LaboratoryGA** [comment]
I switched to using a JavaScript library to handle this, and the encoding problem no longer appears to exist.
