### ISSUE TITLE
Please remove suspension points for the expanded post 

### ISSUE THREAD

**Issue by olganovosad** [LaboratoryGA/cla-cmp-fb-tweet#7]
Hello,

When you expand the post, suspension points are showing up in the beginning of the post.

Please see screenshot:

![suspensionpoints](https://cloud.githubusercontent.com/assets/8656805/7562461/760683dc-f7cc-11e4-8b2b-d69c4e587bd1.png)

**Comment by LaboratoryGA** [comment]
Fixed
