### ISSUE TITLE
Expand post - text is displaying "Caption title Caption description"

### ISSUE THREAD

**Issue by olganovosad** [LaboratoryGA/cla-cmp-fb-tweet#8]
Hello,

When I expand a post there is text is displaying:

Caption title
Caption description

I'm not sure what information should be here, this is not shared post.

![postdetails](https://cloud.githubusercontent.com/assets/8656805/7562515/f874a902-f7cc-11e4-833c-e1178f5b2b3a.png)

**Comment by LaboratoryGA** [comment]
fixed
