### ISSUE TITLE
Some tags are not clickable in the post

### ISSUE THREAD

**Issue by olganovosad** [LaboratoryGA/cla-cmp-fb-tweet#9]
Hello,

Some of the tags are not clickable for some reason.

Please see screenshot:

![tagsfb](https://cloud.githubusercontent.com/assets/8656805/7562617/b48a7f72-f7cd-11e4-9b9d-fb649f1fa299.png)

**Comment by LaboratoryGA** [comment]
Since hashtags support is not included in the FB API, I am simply going to remove all support for it.

**Comment by LaboratoryGA** [comment]
Hashtag support removed
